# Generated by Django 2.0.2 on 2018-03-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registerEntery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('dateOfBirth', models.DateTimeField(null='false')),
                ('emailId', models.EmailField(max_length=254)),
                ('phoneNo', models.IntegerField(max_length=10)),
            ],
        ),
    ]
