# Generated by Django 2.0.2 on 2018-03-10 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerentery',
            name='phoneNo',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
